a=int(input("PLEASE GIVE A NUMBER A TO FIND PYTHOGARAS THEOREM IS TRUE OR NOT:" ))
b=int(input("PLEASE GIVE A NUMBER B TO FIND PYTHOGARAS THEOREM IS TRUE OR NOT:"))
c=int(input("PLEASE GIVE A NUMBER C TO FIND PYTHOGARAS THEOREM IS TRUE OR NOT:"))
if a*a +b*b == c*c:
    print("PYTHOGARAS THEOREM IS TRUE")
else:    
    print("PYTHOGARAS THEOREM IS NOT TRUE")